#if UNITY_EDITOR
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using Orbiters.Toolkit.Editor.Refit;
using Orbiters.Toolkit.Editor.VRChat.Refit;
using UnityEditor;
using UnityEngine;

/// <summary>
/// MCB's side of the Orbiters refit tools. MCB knows the applied custom base of an avatar: its body meshes (by the base
/// FBX files), its blendshapes and the original base it was made from. It tells the other tools (My Avatar) through
/// <see cref="CustomBases"/>, runs its ReFit panel, and restores refitted meshes when resetting to the original base.
/// Refits, their records and the build-time blendshape links are Orbiters Toolkit's (RefitRunner, RefitRecords,
/// RefitBuild); the ReFit package computes the geometry.
/// </summary>
public static partial class MCBReFitIntegration
{
    public const string ToolName = "MCB";

    // Base FBX meshes by name, per MCB component: loading an FBX's sub-assets on every UI refresh is wasteful.
    private static readonly Dictionary<int, (string signature, Dictionary<string, Mesh> meshes)> BaseMeshCache =
        new Dictionary<int, (string, Dictionary<string, Mesh>)>();

    public static bool IsReFitAvailable => RefitEngine.Available;

    /// <summary>The avatar root the refit records of this avatar use.</summary>
    public static Transform Root(MyCustomBase target) => RefitRecords.AvatarRoot(target.transform);

    // ------------------------------------------------------------------
    // Candidates and body
    // ------------------------------------------------------------------

    /// <summary>
    /// All skinned meshes on the avatar that are NOT part of its base body: the clothing and accessories ReFit can adapt.
    /// A renderer is part of the body when a mesh of the same name exists in one of the base FBX files (by name, so it
    /// still works after a version swapped Body/Tail/Hair for native-mesh assets).
    /// </summary>
    public static List<SkinnedMeshRenderer> GetRefitCandidates(MyCustomBase target)
    {
        var result = new List<SkinnedMeshRenderer>();
        if (target == null) return result;
        var baseMeshes = BuildBaseMeshMap(target);
        var root = Root(target);
        foreach (var smr in root.GetComponentsInChildren<SkinnedMeshRenderer>(true))
        {
            if (smr == null || smr.sharedMesh == null || RefitCandidates.IsEditorHelper(smr) || IsBodyRenderer(smr, baseMeshes)
                || IsVersionRenderer(target, root, smr)) continue;
            result.Add(smr);
        }
        return result;
    }

    /// <summary>
    /// Renderers the applied version brings or maps (e.g. Ultirex's feather meshes on a one-mesh Rexouium) are part of
    /// the custom base, not clothing, even when the avatar's original model has no mesh of that name.
    /// </summary>
    private static bool IsVersionRenderer(MyCustomBase target, Transform root, SkinnedMeshRenderer smr)
    {
        if (target.nativeGeneratedRenderers.Contains(smr.gameObject)) return true;
        var layout = target.appliedCustomization?.rendererLayout;
        if (layout == null || layout.IsEmpty) return false;
        string path = GetRendererPath(root, smr.transform);
        return layout.renderers.Any(r => r.path == path);
    }

    /// <summary>Hierarchy path of a renderer relative to the avatar root (Transform.Find compatible).</summary>
    public static string GetRendererPath(Transform root, Transform t) => SmrPathService.GetRelativeTransformPath(root, t);

    /// <summary>True when the renderer currently uses a mesh generated by a refit.</summary>
    public static bool IsRefitApplied(SkinnedMeshRenderer smr) => RefitRecords.IsApplied(smr);

    /// <summary>Name -> Mesh of every mesh found in the avatar's base FBX files.</summary>
    private static Dictionary<string, Mesh> BuildBaseMeshMap(MyCustomBase target)
    {
        if (target == null) return new Dictionary<string, Mesh>(StringComparer.OrdinalIgnoreCase);
        string signature = string.Join("|", target.baseFbxFiles.Select(f => f != null ? f.GetInstanceID() : 0));
        if (BaseMeshCache.TryGetValue(target.GetInstanceID(), out var cached) && cached.signature == signature &&
            cached.meshes.Values.All(m => m != null))
            return cached.meshes;
        var baseMeshes = new Dictionary<string, Mesh>(StringComparer.OrdinalIgnoreCase);
        foreach (var fbx in target.baseFbxFiles)
        {
            if (fbx == null) continue;
            string path = AssetDatabase.GetAssetPath(fbx);
            if (string.IsNullOrEmpty(path)) continue;
            foreach (var obj in AssetDatabase.LoadAllAssetsAtPath(path))
                if (obj is Mesh m && !baseMeshes.ContainsKey(m.name)) baseMeshes[m.name] = m;
        }
        BaseMeshCache[target.GetInstanceID()] = (signature, baseMeshes);
        return baseMeshes;
    }

    /// <summary>A renderer is part of the base body when its mesh maps to a base FBX mesh by name.</summary>
    private static bool IsBodyRenderer(SkinnedMeshRenderer smr, Dictionary<string, Mesh> baseMeshes) =>
        smr != null && smr.sharedMesh != null && ResolveBaseMesh(baseMeshes, smr.sharedMesh.name, smr.transform.name) != null;

    /// <summary>Finds the base FBX mesh corresponding to a (possibly version-swapped) renderer, by name.</summary>
    private static Mesh ResolveBaseMesh(Dictionary<string, Mesh> baseMeshes, string currentMeshName, string rendererName)
    {
        if (baseMeshes == null) return null;
        string clean = CleanMeshName(currentMeshName);
        if (baseMeshes.TryGetValue(clean, out var m)) return m;
        int dot = clean.IndexOf('.');
        if (dot > 0 && baseMeshes.TryGetValue(clean.Substring(0, dot), out m)) return m;
        if (!string.IsNullOrEmpty(rendererName) && baseMeshes.TryGetValue(rendererName, out m)) return m;
        return null;
    }

    private static string CleanMeshName(string name) => (name ?? string.Empty).Replace("(Clone)", "").Replace("_ReFit", "").Trim();

    /// <summary>The body renderer carrying the custom base: the largest mesh of the base body.</summary>
    private static SkinnedMeshRenderer FindPrimaryBodyRenderer(Transform root, Dictionary<string, Mesh> baseMeshes)
    {
        SkinnedMeshRenderer primary = null;
        int bestVerts = -1;
        foreach (var smr in root.GetComponentsInChildren<SkinnedMeshRenderer>(true))
        {
            if (!IsBodyRenderer(smr, baseMeshes)) continue;
            if (smr.sharedMesh.vertexCount > bestVerts)
            {
                bestVerts = smr.sharedMesh.vertexCount;
                primary = smr;
            }
        }
        return primary;
    }

    // ------------------------------------------------------------------
    // The applied custom base, for the Orbiters tools
    // ------------------------------------------------------------------

    internal static bool HasAppliedVersion(MyCustomBase target) =>
        target != null && (target.appliedCustomBaseVersion != null || !string.IsNullOrEmpty(target.appliedCustomBaseVersionString));

    /// <summary>The applied version's declared blendshapes (from the serialized cache once the version object is gone).</summary>
    private static IEnumerable<string> DeclaredShapes(MyCustomBase target)
    {
        if (target.appliedCustomBaseVersion?.customBlendshapes != null)
            return target.appliedCustomBaseVersion.customBlendshapes.Where(e => e != null).Select(e => e.name);
        return (target.appliedVersionBlendshapeLinksCache ?? new List<CreatorBlendshapeEntry>()).Where(e => e != null).Select(e => e.name);
    }

    /// <summary>The blendshapes clothing follows on this custom base: its declared shapes, then the body's flexing shapes.</summary>
    internal static List<string> CollectRefitBlendShapeNames(MyCustomBase target, Mesh targetBodyMesh) =>
        CustomBases.Shapes(target != null ? DeclaredShapes(target) : null, targetBodyMesh);

    internal static string BaseKey(CustomBaseVersion version) =>
        version == null ? null : "mcb:" + version.assetId + ":" + version.version + "|" + version.defaultAviVersion +
                                 (string.IsNullOrEmpty(version.sourceVersionKey) ? "" : "|" + version.sourceVersionKey);

    internal static string DisplayName(MyCustomBase target, CustomBaseVersion version)
    {
        string name = string.IsNullOrWhiteSpace(target.appliedCustomBaseName) ? "Custom base" : target.appliedCustomBaseName;
        return version == null || string.IsNullOrEmpty(version.version) ? name : name + " " + version.version;
    }

    /// <summary>The applied custom base as the Orbiters tools see it; null when the avatar is on its original base.</summary>
    public static CustomBaseInfo Describe(MyCustomBase target)
    {
        if (!HasAppliedVersion(target)) return null;
        var body = FindPrimaryBodyRenderer(Root(target), BuildBaseMeshMap(target));
        if (body == null) return null;
        var version = GetAppliedRefitVersion(target);
        var fbx = target.baseFbxFiles.FirstOrDefault(f => f != null);
        return new CustomBaseInfo
        {
            Key = BaseKey(version),
            Name = DisplayName(target, version),
            BaseName = fbx != null ? fbx.name : null,
            AssetId = version.assetId,
            Version = version.version,
            Body = body,
            Shapes = CollectRefitBlendShapeNames(target, body.sharedMesh),
            Source = ToolName,
            ResolveOriginal = () => ResolveOriginal(target),
            // Its gallery thumbnail when MCB saved one, else Unity's preview of the base model.
            Thumbnail = () => (target != null ? AvatarAssetDiscoveryService.GetSavedThumbnail(target.appliedCustomBaseAssetId) : null)
                              ?? (fbx != null ? AssetPreview.GetAssetPreview(fbx) : null),
        };
    }

    /// <summary>A version was applied or reset: the other tools check the avatar's clothing again.</summary>
    public static void NotifyCustomBaseChanged(MyCustomBase target)
    {
        if (target == null) return;
        BaseMeshCache.Remove(target.GetInstanceID());
        CustomBases.NotifyChanged(Root(target));
    }

    // ------------------------------------------------------------------
    // Restore (works without ReFit installed)
    // ------------------------------------------------------------------

    /// <summary>Restores every refitted mesh of the avatar and removes their records (resetting to the default base).</summary>
    public static void RestoreOriginalAssetMeshes(MyCustomBase target)
    {
        if (target == null) return;
        int restored = RefitRecords.RemoveAll(Root(target));
        if (restored > 0) MCBLogger.Log($"[MCB] ReFit: restored {restored} asset mesh(es) to their original version.");
    }

    /// <summary>Restores one refitted mesh and stops restoring its saved fit for the applied version.</summary>
    public static void RestoreAsset(MyCustomBase target, SkinnedMeshRenderer renderer)
    {
        var record = RefitRecords.Find(renderer);
        if (target == null || record == null) return;
        DisableSavedFit(target, renderer.transform);
        RefitRecords.Remove(record);
    }

    public static List<string> GetBlendShapeNamesWithTransferredReFit(MyCustomBase target, string sourceBlendShapeName) =>
        target != null ? RefitRecords.ShapeNames(Root(target), sourceBlendShapeName) : new List<string> { sourceBlendShapeName };

    public static bool ApplyBlendShapeWeightWithTransferredReFit(MyCustomBase target, IEnumerable<SkinnedMeshRenderer> renderers,
        string sourceBlendShapeName, float weight) =>
        target != null && RefitRecords.SetWeight(Root(target), renderers, sourceBlendShapeName, weight);

    // ------------------------------------------------------------------
    // Run (MCB's ReFit panel)
    // ------------------------------------------------------------------

    /// <summary>
    /// Re-fits the given meshes from the default base body to the applied version body, with the version's blendshapes.
    /// Heavy geometry runs on a background thread; progress is reported into <paramref name="progressState"/>. On
    /// completion the fits are saved for this version, the scene is saved and the generated files are committed through
    /// Unit Git when available.
    /// </summary>
    public static IEnumerator RunReFitCoroutine(MyCustomBase target, List<SkinnedMeshRenderer> targets,
        VersionApplyProgressState progressState, Action<bool, string> onComplete)
    {
        progressState.Begin("Preparing ReFit...", new Color32(0, 218, 109, 255));
        string error = null;
        CustomBaseInfo info = null;
        CustomBaseOriginal original = null;
        if (!IsReFitAvailable) error = "The ReFit package (orbiters.refit) is not installed.";
        else if ((info = Describe(target)) == null)
            error = "ReFit could not match any of the avatar's meshes to the base FBX. The avatar's body mesh may have been renamed.";
        else
        {
            try { original = info.ResolveOriginal(); }
            catch (Exception ex) { error = ex.Message; }
        }
        if (error != null)
        {
            progressState.Fail();
            Debug.LogWarning("[MCB] ReFit aborted: " + error);
            onComplete?.Invoke(false, error);
            yield break;
        }

        var root = Root(target);
        var batch = new RefitBatch
        {
            Avatar = root, Body = info.Body, Renderers = targets.ToList(), Shapes = info.Shapes, Mode = RefitMode.Fit,
            Original = original, BaseKey = info.Key, BaseName = info.Name, Tool = ToolName, Tightness = RefitPreferences.Tightness,
        };
        RefitBatchResult result = null;
        try
        {
            yield return RefitRunner.Run(batch, (t, label) => progressState.Report(Mathf.Clamp01(t) * 0.95f, label), r => result = r,
                CancellationToken.None);
        }
        finally { original?.Dispose(); }

        var changedPaths = result?.ChangedAssets.ToList() ?? new List<string>();
        try
        {
            SaveVersionFits(target, GetAppliedRefitVersion(target));
            string folder = GetVersionRefitFolder(target, GetAppliedRefitVersion(target));
            if (folder != null && AssetDatabase.IsValidFolder(folder)) changedPaths.Add(folder);
        }
        catch (Exception ex) { Debug.LogWarning("[MCB] ReFit: the fits could not be saved for this version: " + ex.Message); }

        progressState.Report(0.97f, "Saving & committing...");
        AssetDatabase.SaveAssets();
        string scenePath = SaveAvatarScene(root.gameObject);
        int refitted = result?.Refitted ?? 0;
        string commitMessage = refitted > 0 ? CommitReFitChanges(changedPaths, scenePath, refitted) : null;

        var failures = result?.Failed.Select(f => (f.Renderer != null ? f.Renderer.name : "asset") + ": " + f.Outcome.Error).ToList() ?? new List<string>();
        bool success = failures.Count == 0 && refitted > 0;
        if (success) progressState.Complete();
        else progressState.Fail();
        string message = success
            ? $"Re-fitted {refitted} asset(s)." + (string.IsNullOrEmpty(commitMessage) ? string.Empty : $" {commitMessage}")
            : (failures.Count > 0 ? string.Join("\n", failures) : "Nothing was re-fitted.");
        if (!success) Debug.LogWarning("[MCB] ReFit: " + message);
        onComplete?.Invoke(success, message);
    }

    private static string SaveAvatarScene(GameObject avatarRoot)
    {
        try
        {
            var scene = avatarRoot.scene;
            if (!scene.IsValid() || string.IsNullOrEmpty(scene.path)) return null;
            UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);
            UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);
            return scene.path;
        }
        catch (Exception ex)
        {
            MCBLogger.LogWarning($"[MCB] ReFit: could not save the scene: {ex.Message}");
            return null;
        }
    }

    /// <summary>Commits only the ReFit-generated files (and the scene) through Unit Git when installed.</summary>
    private static string CommitReFitChanges(List<string> assetPaths, string scenePath, int meshCount)
    {
        try
        {
            if (assetPaths.Count == 0) return null;
            var paths = new List<string>();
            foreach (var p in assetPaths.Distinct())
            {
                if (AssetDatabase.IsValidFolder(p))
                {
                    foreach (string file in Directory.GetFiles(p, "*", SearchOption.AllDirectories))
                        paths.Add(file.Replace('\\', '/'));
                    AddFolderMetas(paths, p);
                    continue;
                }
                AddWithMeta(paths, p);
                AddFolderMetas(paths, Path.GetDirectoryName(p)?.Replace('\\', '/'));
            }
            if (!string.IsNullOrEmpty(scenePath)) AddWithMeta(paths, scenePath);

            if (UnitGitReleasePublisher.TryCommitFiles(
                "MCB : ReFit",
                $"Re-fitted {meshCount} asset mesh(es) to the applied custom base version.\n" + string.Join("\n", assetPaths),
                paths.Distinct().ToList(),
                out string message,
                out string commitHash))
            {
                MCBLogger.Log($"[MCB] ReFit changes committed via Unit Git: {commitHash}");
                return "Committed via Unit Git.";
            }

            if (UnitGitReleasePublisher.IsUnitGitAvailable)
            {
                MCBLogger.LogWarning($"[MCB] ReFit Unit Git commit failed: {message}");
            }
            return null;
        }
        catch (Exception ex)
        {
            MCBLogger.LogWarning($"[MCB] ReFit Unit Git commit failed: {ex.Message}");
            return null;
        }
    }

    private static void AddWithMeta(List<string> paths, string path)
    {
        if (string.IsNullOrEmpty(path)) return;
        paths.Add(path);
        if (File.Exists(path + ".meta")) paths.Add(path + ".meta");
    }

    private static void AddFolderMetas(List<string> paths, string folder)
    {
        // Include the .meta of each (possibly new) folder up to Assets so fresh folders are committed too.
        while (!string.IsNullOrEmpty(folder) && folder.StartsWith("Assets", StringComparison.OrdinalIgnoreCase) &&
               !string.Equals(folder, "Assets", StringComparison.OrdinalIgnoreCase))
        {
            if (File.Exists(folder + ".meta")) paths.Add(folder + ".meta");
            folder = Path.GetDirectoryName(folder)?.Replace('\\', '/');
        }
    }
}

/// <summary>Tells the Orbiters tools which custom base an avatar with MCB uses.</summary>
internal sealed class McbCustomBaseProvider : ICustomBaseProvider
{
    [InitializeOnLoadMethod]
    private static void Register() => CustomBases.Register(new McbCustomBaseProvider());

    public CustomBaseInfo Describe(Transform avatarRoot)
    {
        var mcb = avatarRoot.GetComponentInChildren<MyCustomBase>(true);
        if (mcb == null) mcb = avatarRoot.GetComponentInParent<MyCustomBase>(true);
        return mcb != null ? MCBReFitIntegration.Describe(mcb) : null;
    }
}
#endif
