#if UNITY_EDITOR
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.SceneManagement;
#if ORBITERS_REFIT
using Orbiters.ReFit;
using Orbiters.ReFit.Editor;
#endif
#if ORBITERS_UNITGIT
using Orbiters.UnitGit.Editor;
#endif

/// <summary>
/// Bridges MCB with the optional ReFit package (orbiters.refit): re-fits the avatar's clothing/accessory
/// meshes from the default base body (mesh A) to the applied custom version body (mesh B), transferring the
/// version's exposed blendshapes. Tracks the original meshes on the <see cref="MyCustomBase"/> component so a
/// reset to the default base restores them (this part works even without ReFit installed), and commits the
/// generated files through Unit Git when available.
/// </summary>
public static class MCBReFitIntegration
{
    public static bool IsReFitAvailable
    {
        get
        {
#if ORBITERS_REFIT
            return true;
#else
            return false;
#endif
        }
    }

    // ------------------------------------------------------------------
    // Candidates
    // ------------------------------------------------------------------

    /// <summary>
    /// All skinned meshes on the avatar that are NOT part of the avatar's base body — i.e. the
    /// clothing/accessories that ReFit can adapt. A renderer is considered part of the body when a mesh of the
    /// same name exists in one of the avatar's base FBX files (this matches by name, so it still works after a
    /// version swapped Body/Tail/Hair for native-mesh assets).
    /// </summary>
    public static List<SkinnedMeshRenderer> GetRefitCandidates(MCBEditor editor)
    {
        var result = new List<SkinnedMeshRenderer>();
        var target = editor != null ? editor.customBaseTarget : null;
        if (target == null) return result;
        var root = target.transform.root;
        var baseMeshes = BuildBaseMeshMap(target);

        foreach (var smr in root.GetComponentsInChildren<SkinnedMeshRenderer>(true))
        {
            if (smr == null || smr.sharedMesh == null) continue;
            if (IsBodyRenderer(smr, baseMeshes)) continue; // part of the base body (Body, Tail, Hair, ...)
            result.Add(smr);
        }
        return result;
    }

    /// <summary>Name -> Mesh of every skinned mesh found in the avatar's base FBX files.</summary>
    private static Dictionary<string, Mesh> BuildBaseMeshMap(MyCustomBase target)
    {
        var baseMeshes = new Dictionary<string, Mesh>(StringComparer.OrdinalIgnoreCase);
        if (target == null) return baseMeshes;
        foreach (var fbx in target.baseFbxFiles)
        {
            if (fbx == null) continue;
            string path = AssetDatabase.GetAssetPath(fbx);
            if (string.IsNullOrEmpty(path)) continue;
            foreach (var obj in AssetDatabase.LoadAllAssetsAtPath(path))
                if (obj is Mesh m && !baseMeshes.ContainsKey(m.name)) baseMeshes[m.name] = m;
        }
        return baseMeshes;
    }

    /// <summary>A renderer is part of the base body when its mesh maps to a base FBX mesh by name.</summary>
    private static bool IsBodyRenderer(SkinnedMeshRenderer smr, Dictionary<string, Mesh> baseMeshes)
    {
        return smr != null && smr.sharedMesh != null &&
               ResolveBaseMesh(baseMeshes, smr.sharedMesh.name, smr.transform.name) != null;
    }

    /// <summary>Finds the base FBX mesh corresponding to a (possibly version-swapped) renderer, by name.</summary>
    private static Mesh ResolveBaseMesh(Dictionary<string, Mesh> baseMeshes, string currentMeshName, string rendererName)
    {
        if (baseMeshes == null) return null;
        string clean = (currentMeshName ?? string.Empty).Replace("(Clone)", "").Replace("_ReFit", "").Trim();
        if (baseMeshes.TryGetValue(clean, out var m)) return m;
        int dot = clean.IndexOf('.');
        if (dot > 0 && baseMeshes.TryGetValue(clean.Substring(0, dot), out m)) return m;
        if (!string.IsNullOrEmpty(rendererName) && baseMeshes.TryGetValue(rendererName, out m)) return m;
        return null;
    }

    /// <summary>Hierarchy path of a renderer relative to the avatar root (Transform.Find compatible).</summary>
    public static string GetRendererPath(Transform root, Transform t)
    {
        return SmrPathService.GetRelativeTransformPath(root, t);
    }

    public static RefitAppliedMeshEntry FindEntry(MyCustomBase target, string rendererPath)
    {
        if (target == null || target.appliedRefits == null) return null;
        return target.appliedRefits.FirstOrDefault(e => e != null && e.rendererPath == rendererPath);
    }

    /// <summary>True when the renderer currently uses a mesh generated by ReFit.</summary>
    public static bool IsRefitApplied(MyCustomBase target, SkinnedMeshRenderer smr)
    {
        if (target == null || smr == null) return false;
        var entry = FindEntry(target, GetRendererPath(target.transform.root, smr.transform));
        return entry != null && entry.refitMesh != null && smr.sharedMesh == entry.refitMesh;
    }

    // ------------------------------------------------------------------
    // Reset restore (works without ReFit installed)
    // ------------------------------------------------------------------

    /// <summary>
    /// Restores every ReFit-modified asset mesh back to its original mesh and clears the tracking list.
    /// Called when resetting the avatar to the default original base.
    /// </summary>
    public static void RestoreOriginalAssetMeshes(MyCustomBase target)
    {
        if (target == null || target.appliedRefits == null || target.appliedRefits.Count == 0) return;
        var root = target.transform.root;
        int restored = 0;
        foreach (var entry in target.appliedRefits)
        {
            if (entry == null || entry.originalMesh == null || string.IsNullOrEmpty(entry.rendererPath)) continue;
            var t = root.Find(entry.rendererPath);
            var smr = t != null ? t.GetComponent<SkinnedMeshRenderer>() : null;
            if (smr == null) continue;
            Undo.RecordObject(smr, "MCB ReFit restore");
            smr.sharedMesh = entry.originalMesh;
            restored++;
        }
        Undo.RecordObject(target, "MCB ReFit restore");
        target.appliedRefits.Clear();
        EditorUtility.SetDirty(target);
        MCBLogger.Log($"[MCB] ReFit: restored {restored} asset mesh(es) to their original version.");
    }

#if ORBITERS_REFIT
    // ------------------------------------------------------------------
    // Source avatar (mesh A = default base body, on the SAME skeleton)
    // ------------------------------------------------------------------

    /// <summary>
    /// Builds the source avatar (model A) for ReFit: a hidden clone of the scene avatar whose targeted body
    /// renderers have their meshes swapped back to the DEFAULT base meshes from the avatar's base FBX files.
    /// Because it is a clone of the scene avatar, it shares the exact skeleton, scale and pose of the target —
    /// so the asset binds and re-fits cleanly, with no scale/armature mismatch. Caller must destroy the clone.
    /// </summary>
    public static GameObject BuildSourceClone(MyCustomBase mcb, out string primaryBodyPath, out string error)
    {
        primaryBodyPath = null;
        error = null;
        var root = mcb.transform.root;

        var baseMeshes = BuildBaseMeshMap(mcb);
        if (baseMeshes.Count == 0)
        {
            error = "ReFit could not find any mesh in the avatar's base FBX file(s). Make sure the MCB component's " +
                    "'Base Fbx Files' list points at the avatar's base FBX.";
            Debug.LogWarning("[MCB] ReFit: " + error);
            return null;
        }

        // Body renderers = those whose mesh maps to a base FBX mesh by name. Primary = the largest one.
        var bodyRenderers = new List<SkinnedMeshRenderer>();
        SkinnedMeshRenderer primary = null;
        int bestVerts = -1;
        foreach (var smr in root.GetComponentsInChildren<SkinnedMeshRenderer>(true))
        {
            if (!IsBodyRenderer(smr, baseMeshes)) continue;
            bodyRenderers.Add(smr);
            if (smr.sharedMesh.vertexCount > bestVerts)
            {
                bestVerts = smr.sharedMesh.vertexCount;
                primary = smr;
                primaryBodyPath = GetRendererPath(root, smr.transform);
            }
        }
        if (primary == null)
        {
            error = "ReFit could not match any of the avatar's meshes to the base FBX (looked for meshes named like " +
                    string.Join(", ", baseMeshes.Keys.Take(6)) +
                    (baseMeshes.Count > 6 ? ", ..." : string.Empty) +
                    "). The avatar's body mesh may have been renamed.";
            Debug.LogWarning("[MCB] ReFit: " + error);
            return null;
        }

        var clone = UnityEngine.Object.Instantiate(root.gameObject);
        clone.name = root.name + "__ReFitSource";
        clone.hideFlags = HideFlags.HideAndDontSave;
        clone.SetActive(false);
        foreach (var behaviour in clone.GetComponentsInChildren<Behaviour>(true))
        {
            try { if (!(behaviour is Transform)) behaviour.enabled = false; }
            catch { /* harmless */ }
        }

        int swapped = 0;
        foreach (var smr in bodyRenderers)
        {
            var path = GetRendererPath(root, smr.transform);
            var t = clone.transform.Find(path);
            var cloneSmr = t != null ? t.GetComponent<SkinnedMeshRenderer>() : null;
            if (cloneSmr == null || cloneSmr.sharedMesh == null) continue;
            var baseMesh = ResolveBaseMesh(baseMeshes, cloneSmr.sharedMesh.name, t.name);
            if (baseMesh != null && baseMesh != cloneSmr.sharedMesh) { cloneSmr.sharedMesh = baseMesh; swapped++; }
        }
        if (swapped == 0)
            Debug.LogWarning("[MCB] ReFit: no body mesh differed from the base FBX, so the mesh re-fit is a no-op (only blendshapes will transfer).");

        return clone;
    }

    // ------------------------------------------------------------------
    // Run
    // ------------------------------------------------------------------

    /// <summary>
    /// Re-fits the given asset renderers from the default base body to the current version body, transferring
    /// the version's exposed blendshapes. Heavy geometry runs on a background thread; progress is reported into
    /// <paramref name="progressState"/> (drives the integrated progress button). On completion the scene and
    /// assets are saved and the generated files are committed through Unit Git when available.
    /// </summary>
    public static IEnumerator RunReFitCoroutine(MCBEditor editor, List<SkinnedMeshRenderer> targets,
        VersionApplyProgressState progressState, Action<bool, string> onComplete)
    {
        var mcb = editor.customBaseTarget;
        var root = mcb.transform.root;
        progressState.Begin("Preparing ReFit...", new Color32(0, 218, 109, 255));

        var shapes = (mcb.appliedCustomBaseVersion != null && mcb.appliedCustomBaseVersion.customBlendshapes != null
                ? mcb.appliedCustomBaseVersion.customBlendshapes
                    .Where(b => b != null && !string.IsNullOrEmpty(b.name))
                    .Select(b => b.name)
                : Enumerable.Empty<string>())
            .Distinct()
            .ToList();

        var source = BuildSourceClone(mcb, out string primaryBodyPath, out string sourceError);
        if (source == null)
        {
            progressState.Fail();
            string msg = sourceError ?? "Could not build the default base reference.";
            Debug.LogWarning("[MCB] ReFit aborted: " + msg);
            onComplete?.Invoke(false, msg);
            yield break;
        }

        var sourceBody = string.IsNullOrEmpty(primaryBodyPath) ? null : source.transform.Find(primaryBodyPath)?.GetComponent<SkinnedMeshRenderer>();
        var targetBody = string.IsNullOrEmpty(primaryBodyPath) ? null : root.Find(primaryBodyPath)?.GetComponent<SkinnedMeshRenderer>();

        var changedPaths = new List<string>();
        var failures = new List<string>();
        int done = 0;

        // Wrap so the temporary source clone is always destroyed, even on early exit.
        var enumerator = RefitTargets(editor, mcb, root, source, sourceBody, targetBody, shapes, targets,
            progressState, changedPaths, failures, v => done = v);
        while (true)
        {
            bool moved;
            try { moved = enumerator.MoveNext(); }
            catch (Exception ex)
            {
                if (source != null) UnityEngine.Object.DestroyImmediate(source);
                progressState.Fail();
                Debug.LogError($"[MCB] ReFit failed: {ex}");
                onComplete?.Invoke(false, $"ReFit failed: {ex.Message}");
                yield break;
            }
            if (!moved) break;
            yield return enumerator.Current;
        }

        if (source != null) UnityEngine.Object.DestroyImmediate(source);

        // Save + commit
        progressState.Report(0.97f, "Saving & committing...");
        AssetDatabase.SaveAssets();
        string scenePath = SaveAvatarScene(root.gameObject);
        string commitMessage = CommitReFitChanges(changedPaths, scenePath, changedPaths.Count);

        bool success = failures.Count == 0 && changedPaths.Count > 0;
        if (success) progressState.Complete();
        else progressState.Fail();

        string message = success
            ? $"Re-fitted {changedPaths.Count} asset(s)." + (string.IsNullOrEmpty(commitMessage) ? string.Empty : $" {commitMessage}")
            : (failures.Count > 0 ? string.Join("\n", failures) : "Nothing was re-fitted.");
        if (!success) Debug.LogWarning("[MCB] ReFit: " + message);
        onComplete?.Invoke(success, message);
    }

    private static IEnumerator RefitTargets(MCBEditor editor, MyCustomBase mcb, Transform root,
        GameObject source, SkinnedMeshRenderer sourceBody, SkinnedMeshRenderer targetBody, List<string> shapes,
        List<SkinnedMeshRenderer> targets, VersionApplyProgressState progressState,
        List<string> changedPaths, List<string> failures, Action<int> reportDone)
    {
        int done = 0;
        foreach (var renderer in targets)
        {
            if (renderer == null || renderer.sharedMesh == null) { reportDone(++done); continue; }
            string rendererPath = GetRendererPath(root, renderer.transform);

            // Re-running: recompute from the clean original mesh instead of stacking refits.
            var existing = FindEntry(mcb, rendererPath);
            if (existing != null && existing.originalMesh != null && renderer.sharedMesh != existing.originalMesh)
            {
                Undo.RecordObject(renderer, "MCB ReFit");
                renderer.sharedMesh = existing.originalMesh;
            }
            var originalMesh = renderer.sharedMesh;

            var request = new ReFitRequest
            {
                mode = shapes.Count > 0 ? ReFitMode.MeshAndBlendshape : ReFitMode.MeshToMesh,
                assetRenderer = renderer,
                sourceAvatar = source,
                targetAvatar = root.gameObject,
                sourceBodyRenderer = sourceBody,
                targetBodyRenderer = targetBody,
                targetBlendshapes = shapes,
                settings = new ReFitSettings
                {
                    replaceArmature = false,     // the asset already lives on this avatar's armature
                    transferWeights = false,
                    prefixTransferredShapes = false, // keep exact body shape names so links/animations match
                    savePrefab = false
                }
            };

            float baseT = (float)done / targets.Count;
            float slice = 1f / targets.Count;
            ReFitResult result = null;
            yield return ReFitService.ExecuteCoroutine(
                request,
                (t, label) => progressState.Report(baseT + Mathf.Clamp01(t) * slice * 0.95f, $"{renderer.name}: {label}"),
                r => result = r);

            if (result != null && result.success)
            {
                if (existing == null)
                {
                    existing = new RefitAppliedMeshEntry { rendererPath = rendererPath, originalMesh = originalMesh };
                    mcb.appliedRefits.Add(existing);
                }
                if (existing.originalMesh == null) existing.originalMesh = originalMesh;
                existing.refitMesh = result.mesh;
                existing.refitMeshAssetPath = result.meshAssetPath;
                if (!string.IsNullOrEmpty(result.meshAssetPath)) changedPaths.Add(result.meshAssetPath);
                EditorUtility.SetDirty(mcb);
            }
            else
            {
                string detail = result != null
                    ? string.Join("; ", result.report.messages.Where(m => m.severity == ReFitSeverity.Error).Select(m => m.text))
                    : "unknown error";
                failures.Add($"{renderer.name}: {detail}");
            }
            reportDone(++done);
        }
    }

    /// <summary>Restores a single asset renderer to its original mesh and drops it from the tracking list.</summary>
    public static void RestoreAsset(MyCustomBase mcb, string rendererPath)
    {
        if (mcb == null) return;
        var entry = FindEntry(mcb, rendererPath);
        if (entry == null) return;
        var root = mcb.transform.root;
        var t = root.Find(rendererPath);
        var smr = t != null ? t.GetComponent<SkinnedMeshRenderer>() : null;
        if (smr != null && entry.originalMesh != null)
        {
            Undo.RecordObject(smr, "MCB ReFit restore");
            smr.sharedMesh = entry.originalMesh;
        }
        Undo.RecordObject(mcb, "MCB ReFit restore");
        mcb.appliedRefits.Remove(entry);
        EditorUtility.SetDirty(mcb);
    }

    private static string SaveAvatarScene(GameObject avatarRoot)
    {
        try
        {
            var scene = avatarRoot.scene;
            if (!scene.IsValid() || string.IsNullOrEmpty(scene.path)) return null;
            UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);
            UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);
            return scene.path;
        }
        catch (Exception ex)
        {
            MCBLogger.LogWarning($"[MCB] ReFit: could not save the scene: {ex.Message}");
            return null;
        }
    }

    /// <summary>Commits only the ReFit-generated files (and the scene) through Unit Git when installed.</summary>
    private static string CommitReFitChanges(List<string> meshAssetPaths, string scenePath, int meshCount)
    {
#if ORBITERS_UNITGIT
        try
        {
            if (meshAssetPaths.Count == 0) return null;
            var paths = new List<string>();
            foreach (var p in meshAssetPaths)
            {
                AddWithMeta(paths, p);
                AddFolderMetas(paths, Path.GetDirectoryName(p)?.Replace('\\', '/'));
            }
            if (!string.IsNullOrEmpty(scenePath)) AddWithMeta(paths, scenePath);

            var result = UnitGitReleases.CommitFiles(
                "MCB : ReFit",
                $"Re-fitted {meshCount} asset mesh(es) to the applied custom base version.\n" +
                string.Join("\n", meshAssetPaths),
                paths.Distinct().ToArray());
            if (result.Success)
            {
                MCBLogger.Log($"[MCB] ReFit changes committed via Unit Git: {result.CommitHash}");
                return "Committed via Unit Git.";
            }
            MCBLogger.LogWarning($"[MCB] ReFit Unit Git commit failed: {result.Message}");
            return null;
        }
        catch (Exception ex)
        {
            MCBLogger.LogWarning($"[MCB] ReFit Unit Git commit failed: {ex.Message}");
            return null;
        }
#else
        return null;
#endif
    }

#if ORBITERS_UNITGIT
    private static void AddWithMeta(List<string> paths, string path)
    {
        if (string.IsNullOrEmpty(path)) return;
        paths.Add(path);
        if (File.Exists(path + ".meta")) paths.Add(path + ".meta");
    }

    private static void AddFolderMetas(List<string> paths, string folder)
    {
        // Include the .meta of each (possibly new) folder up to Assets so fresh folders are committed too.
        while (!string.IsNullOrEmpty(folder) && folder.StartsWith("Assets", StringComparison.OrdinalIgnoreCase) &&
               !string.Equals(folder, "Assets", StringComparison.OrdinalIgnoreCase))
        {
            if (File.Exists(folder + ".meta")) paths.Add(folder + ".meta");
            folder = Path.GetDirectoryName(folder)?.Replace('\\', '/');
        }
    }
#endif
#endif // ORBITERS_REFIT
}
#endif
