#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;

/// <summary>
/// Bridges MCB version publication with Unit Git when the optional Unit Git package is present.
/// The reflection details live in UnitGitReleaseApiBinding so this publisher only depends on the
/// current Unit Git release API contract.
/// </summary>
public static class UnitGitReleasePublisher
{
    public static bool IsUnitGitAvailable
    {
        get { return string.IsNullOrEmpty(UnitGitAvailabilityMessage); }
    }

    public static string UnitGitAvailabilityMessage
    {
        get
        {
            return TryBindReleaseApi(
                out _,
                out string message,
                UnitGitReleaseApiBinding.CommitFilesCapability,
                UnitGitReleaseApiBinding.ScopedReleaseCheckpointCapability)
                ? string.Empty
                : message;
        }
    }

    /// <summary>
    /// Connector test: generates a small dummy file and commits it through Unit Git, so the
    /// MCB <-> Unit Git integration can be verified without publishing anything.
    /// </summary>
    public static bool TryCreateTestCommit(out string message)
    {
        message = string.Empty;
        if (!TryBindReleaseApi(out var api, out message, UnitGitReleaseApiBinding.CommitFilesCapability))
        {
            return false;
        }

        try
        {
            string folder = "Assets/MCB/unitgit-test";
            Directory.CreateDirectory(folder);
            string fileName = $"unitgit-test-{DateTime.Now:yyyy-MM-dd_HH-mm-ss}.txt";
            string filePath = folder + "/" + fileName;
            File.WriteAllText(
                filePath,
                "Unit Git connector test file generated by MCB.\n" +
                $"Created: {DateTime.Now:O}\n" +
                "This file only exists to verify that MCB can create commits through Unit Git. It is safe to delete.\n");
            AssetDatabase.ImportAsset(filePath);

            var pathsToCommit = new List<string> { filePath };
            if (File.Exists(filePath + ".meta")) pathsToCommit.Add(filePath + ".meta");
            if (File.Exists(folder + ".meta")) pathsToCommit.Add(folder + ".meta");

            UnitGitReleaseApiResult result = api.CommitFiles(
                "MCB : Unit Git connector test",
                $"Generated test file: {filePath}",
                pathsToCommit.ToArray());

            message = result.Success
                ? $"Test commit created ({ShortHash(result.CommitHash)}) with {fileName}."
                : result.Message;

            if (result.Success)
            {
                MCBLogger.Log($"[MCB] Unit Git connector test commit created: {result.CommitHash}");
            }
            else
            {
                MCBLogger.LogWarning($"[MCB] Unit Git connector test commit failed: {result.Message}");
            }

            return result.Success;
        }
        catch (Exception ex)
        {
            message = ex.Message;
            MCBLogger.LogWarning($"[MCB] Unit Git connector test commit failed: {message}");
            return false;
        }
    }

    private static string ShortHash(string hash)
    {
        return string.IsNullOrEmpty(hash) ? "?" : (hash.Length > 8 ? hash.Substring(0, 8) : hash);
    }

    public static bool TryCommitFiles(
        string commitTitle,
        string trailingParagraph,
        IEnumerable<string> projectRelativePaths,
        out string message,
        out string commitHash)
    {
        message = string.Empty;
        commitHash = string.Empty;
        if (!TryBindReleaseApi(out var api, out message, UnitGitReleaseApiBinding.CommitFilesCapability))
        {
            return false;
        }

        string[] paths = (projectRelativePaths ?? Enumerable.Empty<string>())
            .Where(path => !string.IsNullOrWhiteSpace(path))
            .Distinct(StringComparer.Ordinal)
            .ToArray();
        if (paths.Length == 0)
        {
            message = "At least one file path is required.";
            return false;
        }

        try
        {
            UnitGitReleaseApiResult result = api.CommitFiles(commitTitle, trailingParagraph, paths);
            message = result.Message;
            commitHash = result.CommitHash;
            return result.Success;
        }
        catch (Exception ex)
        {
            message = ex.Message;
            return false;
        }
    }

    /// <summary>
    /// Saves pending assets and asks Unit Git to record a release checkpoint when Unit Git is present.
    /// Missing Unit Git is a no-op: the publish itself has already succeeded and should not report a warning.
    /// </summary>
    public static bool TryPublishReleaseCheckpoint(CustomBaseVersion version, string assetName, out string message)
    {
        message = string.Empty;
        if (!TryBindReleaseApi(
                out var api,
                out message,
                UnitGitReleaseApiBinding.ScopedReleaseCheckpointCapability))
        {
            return false;
        }

        try
        {
            EditorUtility.DisplayProgressBar("Unit Git", "Creating release checkpoint commit...", 0.9f);
            AssetDatabase.SaveAssets();

            object entry = api.CreateReleaseEntry();
            api.SetReleaseEntryValue(entry, "tool", "MCB");
            api.SetReleaseEntryValue(entry, "type", "mcb-version");
            api.SetReleaseEntryValue(entry, "name", string.IsNullOrWhiteSpace(assetName) ? "MCB Asset" : assetName.Trim());
            api.SetReleaseEntryValue(entry, "version", version?.version ?? string.Empty);
            api.SetReleaseEntryValue(entry, "title", version?.title ?? string.Empty);
            api.SetReleaseEntryValue(entry, "changelog", version?.changelog ?? string.Empty);
            api.SetReleaseEntryValue(entry, "scope", version != null ? version.scope.ToString() : string.Empty);
            api.SetReleaseEntryValue(entry, "date", DateTime.UtcNow.ToString("o"));

            if (version != null)
            {
                if (version.assetId > 0)
                {
                    api.AddReleaseField(entry, "Asset Id", version.assetId.ToString());
                }

                if (!string.IsNullOrWhiteSpace(version.defaultAviVersion))
                {
                    api.AddReleaseField(entry, "Default Avatar Version", version.defaultAviVersion);
                }

                if (!string.IsNullOrWhiteSpace(version.parentVersion))
                {
                    api.AddReleaseField(entry, "Parent Version", version.parentVersion);
                }
            }

            string entryVersion = api.GetReleaseEntryString(entry, "version");
            string entryTitle = api.GetReleaseEntryString(entry, "title");
            string commitTitle = $"MCB : v{entryVersion} - {entryTitle}";
            UnitGitReleaseApiResult result = api.PublishRelease(entry, commitTitle, BuildReleaseCheckpointPaths(version));

            message = result.Message;
            if (result.Success)
            {
                MCBLogger.Log($"[CreatorMode] Unit Git release checkpoint created for v{entryVersion} (commit {result.CommitHash}).");
            }
            else if (OperationErrorClassifier.IsDiskFullMessage(message))
            {
                message = OperationErrorReporter.Report(null, new OperationError
                {
                    Category = OperationErrorCategory.DiskFull,
                    UserMessage = DiskUtils.BuildDiskFullMessage("Creating the Unit Git release checkpoint"),
                    Detail = message
                }, "Unit Git checkpoint");
                MCBLogger.LogWarning($"[CreatorMode] Unit Git release checkpoint failed (disk full): {message}");
            }
            else
            {
                MCBLogger.LogWarning($"[CreatorMode] Unit Git release checkpoint failed: {message}");
            }

            return result.Success;
        }
        catch (Exception ex)
        {
            if (OperationErrorClassifier.IsDiskFullError(ex))
            {
                message = OperationErrorReporter.Report(null, new OperationError
                {
                    Category = OperationErrorCategory.DiskFull,
                    UserMessage = DiskUtils.BuildDiskFullMessage("Creating the Unit Git release checkpoint"),
                    Detail = ex.ToString()
                }, "Unit Git checkpoint");
            }
            else
            {
                message = ex.Message;
            }

            MCBLogger.LogWarning($"[CreatorMode] Unit Git release checkpoint failed: {ex.Message}");
            return false;
        }
        finally
        {
            EditorUtility.ClearProgressBar();
        }
    }

    private static bool TryBindReleaseApi(
        out UnitGitReleaseApiBinding api,
        out string message,
        params string[] requiredCapabilities)
    {
        return UnitGitReleaseApiBinding.TryCreateInstalled(requiredCapabilities, out api, out message);
    }

    private static string[] BuildReleaseCheckpointPaths(CustomBaseVersion version)
    {
        var paths = new List<string>();
        if (version == null)
        {
            return paths.ToArray();
        }

        string folder = MCBUtils.GetVersionDataPath(version);
        if (string.IsNullOrWhiteSpace(folder))
        {
            return paths.ToArray();
        }

        AddIfExists(paths, MCBUtils.CombineUnityPath(folder, "version.json"));
        AddIfExists(paths, MCBUtils.CombineUnityPath(folder, VersionManifest.FileName));

        VersionManifest manifest = VersionManifest.Load(folder);
        if (manifest != null && manifest.outputs != null)
        {
            foreach (VersionManifestFile output in manifest.outputs)
            {
                if (output == null || string.IsNullOrWhiteSpace(output.path))
                {
                    continue;
                }

                AddIfExists(paths, MCBUtils.CombineUnityPath(folder, output.path));
            }
        }

        return paths
            .Where(path => !string.IsNullOrWhiteSpace(path))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();
    }

    private static void AddIfExists(List<string> paths, string unityPath)
    {
        if (string.IsNullOrWhiteSpace(unityPath))
        {
            return;
        }

        string normalized = MCBUtils.ToUnityPath(unityPath);
        if (File.Exists(Path.GetFullPath(normalized)))
        {
            paths.Add(normalized);
        }

        string metaPath = normalized + ".meta";
        if (File.Exists(Path.GetFullPath(metaPath)))
        {
            paths.Add(metaPath);
        }
    }
}
#endif
